name: Daily Quiz

on:
  schedule:
    - cron: '10 15 * * *'
  workflow_dispatch:

jobs:
  quiz:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run quiz script
        env:
          API_ID: ${{ secrets.TELEGRAM_TOKEN }}
          API_HASH: ${{ secrets.API_HASH }}
          TOKEN_BOT: ${{ secrets.TOKEN_BOT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          AUTHORIZED_USER_ID: ${{ secrets.AUTHORIZED_USER_ID }}
        run: python main.py